theme: jekyll-theme-leap-day

title: DESPASITO
description: "Determining Equilibrium State and Parametrization: Application for SAFT, Intended for Thermodynamic Output"
logo: 
show_downloads: 
google_analytics: 


footer-links:
  github: https://github.com/Santiso-Group/despasito
